#!/bin/bash

cd SWE_2021_41_2023_2_week_4-main
cd files

lower=(q w e r t y u i o p a s d f g h j k l z x c v b n m)
upper=(Q W E R T Y U I O P A S D F G H J K L Z X C V B N M)

shopt -s nullglob

for i in {0..25}
do
  mv ${lower[i]}* /home/workspace/SWE_2021_41_2023_2_week_4-main/${lower[i]}
  mv ${upper[i]}* /home/workspace/SWE_2021_41_2023_2_week_4-main/${lower[i]}
done

